USM/USM/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.dashboard, name='dashboard'),  # Ajoutez cette ligne pour la page d'accueil
    path('', include('filiere.urls')),
    path('etudiant/', include('etudiant.urls')),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_user, name='register'),
    path("logout/", views.logout_view, name="logout"),
]

USM/filiere/models.py
from django.urls import reverse
from djongo import models
from django.utils import timezone

class Filiere(models.Model):
    _id = models.ObjectIdField()
    code = models.CharField(max_length=50)
    intitule = models.CharField(max_length=255)
    etablissement = models.ForeignKey('Etablissement', to_field='_id', on_delete=models.CASCADE)
    ueObligatoires = models.ManyToManyField('UE', related_name='filieres_obligatoires')
    ueOptionnelles = models.ManyToManyField('UE', related_name='filieres_optionnelles')
    responsable = models.ForeignKey('Enseignant', on_delete=models.CASCADE)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_mise_a_jour = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)  # Champ pour suppression douce


    class Meta:
        db_table = "filieres"

    def __str__(self):
        return self.intitule

    def delete(self):
        self.is_deleted = True
        self.save()

    def get_object_id(self):
        return str(self._id)

    def get_absolute_url_edit(self):
        return reverse('filiere_update', kwargs={'id': str(self._id)})

    def get_absolute_url_delete(self):
        return reverse('filiere_delete', kwargs={'id': str(self._id)})

    def get_absolute_url_detail(self):
        return reverse('filiere_detail', kwargs={'id': str(self._id)})


class PersonnelAdministratif(models.Model):
    _id = models.ObjectIdField()
    nom = models.CharField(max_length=255)
    prenom = models.CharField(max_length=100)
    poste = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_mise_a_jour = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)  # Champ pour suppression douce


    class Meta:
        db_table = 'personnels'

    def __str__(self):
        return self.nom

    def delete(self):
        self.is_deleted = True
        self.save()

    def get_object_id(self):
        return str(self._id)

    def get_absolute_url_edit(self):
        return reverse('personnel_update', kwargs={'id': str(self._id)})

    def get_absolute_url_delete(self):
        return reverse('personnel_delete', kwargs={'id': str(self._id)})

    def get_absolute_url_detail(self):
        return reverse('personnel_detail', kwargs={'id': str(self._id)})


class Enseignant(models.Model):
    _id = models.ObjectIdField()
    nom = models.CharField(max_length=255)
    prenom = models.CharField(max_length=100)
    specialite = models.CharField(max_length=255)
    grade = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    ues = models.ManyToManyField('UE')
    date_creation = models.DateTimeField(auto_now_add=True)
    date_mise_a_jour = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)  # Champ pour suppression douce


    class Meta:
        db_table = 'enseignants'


    def get_object_id(self):
        return str(self._id)

    def delete(self):
        self.is_deleted = True
        self.save()

    def get_absolute_url_edit(self):
        return reverse('enseignant_update', kwargs={'id': str(self._id)})

    def get_absolute_url_delete(self):
        return reverse('enseignant_delete', kwargs={'id': str(self._id)})

    def get_absolute_url_detail(self):
        return reverse('enseignant_detail', kwargs={'id': str(self._id)})


class UE(models.Model):
    _id = models.ObjectIdField()
    code = models.CharField(max_length=50)
    intitule = models.CharField(max_length=255)
    description = models.TextField()
    nbCredits = models.IntegerField()
    responsable = models.ForeignKey('Enseignant', on_delete=models.CASCADE)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_mise_a_jour = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)  # Champ pour suppression douce


    class Meta:
        db_table = 'ues'

    def __str__(self):
        return self.intitule

    def delete(self):
        self.is_deleted = True
        self.save()

    def get_object_id(self):
        return str(self._id)

    def get_absolute_url_edit(self):
        return reverse('ue_update', kwargs={'id': str(self._id)})

    def get_absolute_url_delete(self):
        return reverse('ue_delete', kwargs={'id': str(self._id)})

    def get_absolute_url_detail(self):
        return reverse('ue_detail', kwargs={'id': str(self._id)})

class Etablissement(models.Model):
    _id = models.ObjectIdField()
    nom = models.CharField(max_length=100)
    type = models.CharField(max_length=50)
    doyen = models.ForeignKey('Enseignant', on_delete=models.CASCADE)
    is_deleted = models.BooleanField(default=False)  # Champ pour suppression douce


    class Meta:
        db_table = "etablissements"

    def get_object_id(self):
        return str(self._id)

    def delete(self):
        self.is_deleted = True
        self.save()

    def __str__(self):
        return self.nom

    def get_object_id(self):
        return str(self._id)

    def get_absolute_url_edit(self):
        return reverse('etablissement_update', kwargs={'id': str(self._id)})

    def get_absolute_url_delete(self):
        return reverse('etablissement_delete', kwargs={'id': str(self._id)})

    def get_absolute_url_detail(self):
        return reverse('etablissement_detail', kwargs={'id': str(self._id)})

USM/templates/ue/add_ue.html
{% extends 'index.html' %}

{% block content %}
<div class="row">
  <div class="col-md-6 grid-margin stretch-card mx-auto">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Ajouter une UE</h4>
        <form method="post" action="{% url 'ue_create' %}">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_code">Code</label>
            <input type="text" name="code" class="form-control" id="id_code" placeholder="Code">
            {% if form.code.errors %}
              <p class="text-danger">{{ form.code.errors }}</p>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="id_intitule">Intitulé</label>
            <input type="text" name="intitule" class="form-control" id="id_intitule" placeholder="Intitulé">
            {% if form.intitule.errors %}
              <p class="text-danger">{{ form.intitule.errors }}</p>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="id_description">Description</label>
            <textarea name="description" class="form-control" id="id_description" placeholder="Description"></textarea>
            {% if form.description.errors %}
              <p class="text-danger">{{ form.description.errors }}</p>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="id_nbCredits">Nombre de Crédits</label>
            <input type="number" name="nbCredits" class="form-control" id="id_nbCredits" placeholder="Nombre de Crédits">
            {% if form.nbCredits.errors %}
              <p class="text-danger">{{ form.nbCredits.errors }}</p>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="id_responsable">Responsable</label>
            <select name="responsable" class="form-control" id="id_responsable">
              {% for enseignant in enseignants %}
                <option value="{{ enseignant.get_object_id }}">{{ enseignant.nom }} {{ enseignant.prenom }}</option>
              {% endfor %}
            </select>
            {% if form.responsable.errors %}
              <p class="text-danger">{{ form.responsable.errors }}</p>
            {% endif %}
          </div>
          <button type="submit" class="btn btn-primary me-2">Ajouter</button>
          <a href="{% url 'ue_list' %}" class="btn btn-dark">Annuler</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

USM/templates/ue/detail_ue.html
{% extends 'index.html' %}

{% block content %}
<div class="col-md-8 grid-margin stretch-card mx-auto">
    <div class="card">
      <div class="card-body">
        <div class="d-flex flex-row justify-content-between">
          <h4 class="card-title mb-1">Détails de l'Unité d'Enseignement (UE)</h4>
          <a href="{% url 'ue_list' %}" class="btn btn-secondary mb-1">Retour</a>
        </div>
        <div class="row">
          <div class="col-12">
            <div class="preview-list">
              <div class="preview-item border-bottom">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-primary">
                    <i class="mdi mdi-book"></i>
                  </div>
                </div>
                <div class="preview-item-content d-sm-flex flex-grow">
                  <div class="flex-grow">
                    <h6 class="preview-subject">{{ ue.code }}</h6>
                    <p class="text-muted mb-0">{{ ue.intitule }}</p>
                  </div>
                </div>
              </div>
              <div class="preview-item border-bottom">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-info">
                    <i class="mdi mdi-information-outline"></i>
                  </div>
                </div>
                <div class="preview-item-content d-sm-flex flex-grow">
                  <div class="flex-grow">
                    <h6 class="preview-subject">Description</h6>
                    <p class="text-muted mb-0">{{ ue.description }}</p>
                  </div>
                </div>
              </div>
              <!-- Add other details as needed -->
              <!-- You can add more fields similarly -->
            </div>
          </div>
        </div>
        <div class="mt-4 d-flex justify-content-between">
          <a href="{{ ue.get_absolute_url_edit }}" class="btn btn-primary">Modifier</a>
          <a href="{{ ue.get_absolute_url_delete }}" class="btn btn-danger">Supprimer</a>
        </div>
      </div>
    </div>
</div>
{% endblock %}

USM/templates/ue/ue_list.html
{% extends 'index.html' %}

{% block content %}
<div class="row">
  <div class="col-lg-8 mx-auto grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <h4 class="card-title">Liste des Unités d'Enseignement (UE)</h4>
          <a href="{% url 'ue_create' %}" class="btn btn-sm btn-warning">+ Ajouter</a>
        </div>
        {% if ues %}
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>Code</th>
                <th>Intitulé</th>
                <th>Description</th>
                <th class="text-center">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for ue in ues %}
              <tr>
                <td>{{ ue.code }}</td>
                <td>{{ ue.intitule }}</td>
                <td>{{ ue.description }}</td>
                <td class="text-center">
                  <a href="{{ ue.get_absolute_url_detail }}" class="btn btn-sm btn-info">Détails</a>
                  <a href="{{ ue.get_absolute_url_edit }}" class="btn btn-sm btn-primary">Modifier</a>
                  <a href="{{ ue.get_absolute_url_delete }}" class="btn btn-sm btn-danger">Supprimer</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {% else %}
        <div class="text-center mt-4">
          <i class="mdi mdi-alert-circle-outline mdi-48px text-muted"></i>
          <p class="text-muted">Aucune unité d'enseignement n'est disponible pour le moment.</p>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

USM/templates/ue/update_ue.html
{% extends 'index.html' %}

{% block content %}
<div class="row">
  <div class="col-md-6 mx-auto grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Mettre à jour l'Unité d'Enseignement (UE)</h4>
        <form method="post" action="{{ ue.get_absolute_url_edit }}">
          {% csrf_token %}
          <div class="form-group">
            <label for="code">Code</label>
            <input type="text" name="code" class="form-control" id="code" value="{{ ue.code }}" placeholder="Code">
            {% if form.code.errors %}
              <p class="text-danger">{{ form.code.errors }}</p>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="intitule">Intitulé</label>
            <input type="text" name="intitule" class="form-control" id="intitule" value="{{ ue.intitule }}" placeholder="Intitulé">
            {% if form.intitule.errors %}
              <p class="text-danger">{{ form.intitule.errors }}</p>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="description">Description</label>
            <textarea name="description" class="form-control" id="description" placeholder="Description">{{ ue.description }}</textarea>
          </div>
          <button type="submit" class="btn btn-primary me-2">Mettre à jour</button>
          <a href="{% url 'ue_list' %}" class="btn btn-dark">Annuler</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}